# Generated by Django 4.2 on 2024-11-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFM_data',
            fields=[
                ('srno', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('substationid', models.TextField(max_length=255)),
                ('feederid', models.TextField(max_length=255)),
                ('feedername', models.TextField(max_length=255)),
                ('feedercode', models.TextField(max_length=255)),
                ('received_datetime', models.DateTimeField(max_length=255)),
                ('feedertypeid', models.TextField(max_length=255)),
                ('feedervoltageid', models.TextField(max_length=255)),
                ('feederlocationid', models.TextField(max_length=255)),
                ('feedercategoryid', models.TextField(max_length=255)),
                ('voltage_brphase', models.TextField(max_length=255)),
                ('voltage_bphase', models.TextField(max_length=255)),
                ('voltage_ryphase', models.TextField(max_length=255)),
                ('voltage_rphase', models.TextField(max_length=255)),
                ('voltage_ybphase', models.TextField(max_length=255)),
                ('voltage_yphase', models.TextField(max_length=255)),
                ('current_bphase', models.TextField(max_length=255)),
                ('current_rphase', models.TextField(max_length=255)),
                ('current_yphase', models.TextField(max_length=255)),
                ('frequency', models.TextField(max_length=255)),
                ('powerfactor', models.TextField(max_length=255)),
                ('active_power', models.TextField(max_length=255)),
                ('apparent_power', models.TextField(max_length=255)),
                ('active_export', models.TextField(max_length=255)),
                ('active_import', models.TextField(max_length=255)),
                ('reactive_export', models.TextField(max_length=255)),
                ('reactive_import', models.TextField(max_length=255)),
                ('reactive_power', models.TextField(max_length=255)),
                ('lastupdateddatetime', models.DateTimeField(max_length=255)),
                ('systeminsertdatetime', models.TextField(max_length=255)),
                ('oil_temprature', models.TextField(max_length=255)),
                ('tap_position', models.TextField(max_length=255)),
                ('winding_temprature', models.TextField(max_length=255)),
                ('feederiddigit', models.TextField(max_length=255)),
            ],
        ),
    ]
