# Generated by Django 4.2 on 2024-11-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfm_data',
            name='lastupdateddatetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mfm_data',
            name='received_datetime',
            field=models.DateTimeField(),
        ),
    ]
