# Generated by Django 4.2 on 2024-11-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0002_alter_mfm_data_lastupdateddatetime_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mfm_data',
            table='MFM_data',
        ),
    ]
