# Generated by Django 4.2 on 2024-12-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_alter_mfm_data_active_export_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_data',
            fields=[
                ('srno', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('substationid', models.TextField(max_length=255)),
                ('feederid', models.TextField(max_length=255)),
                ('feedername', models.TextField(max_length=255)),
                ('feedercode', models.TextField(max_length=255)),
                ('received_datetime', models.DateTimeField()),
                ('parameter', models.TextField(blank=True, max_length=255, null=True)),
                ('parameter_value', models.TextField(blank=True, max_length=255, null=True)),
                ('lastupdateddatetime', models.DateTimeField()),
                ('systeminsertdatetime', models.TextField(blank=True, max_length=255, null=True)),
                ('feederiddigit', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Event_data',
            },
        ),
    ]
