# Generated by Django 4.2 on 2025-02-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0005_event_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_data',
            name='acknowledge',
            field=models.BooleanField(default=False),
        ),
    ]
